export const ACTION_TYPES = {
  UPDATE_NAME: "UPDATE_NAME",
  GAME_START: "GAME_START",
  GAME_START_ERR: "GAME_START_ERR",
  BOX_START: "BOX_START",
  BOX_MOVE: "BOX_MOVE",
  BOX_STOP: "BOX_STOP",
  
}
